version: '3'
services:
  mariadb:
    image: "bitnami/mariadb:latest"
    volumes:
      - ./docker/db:/bitnami/mariadb
    environment:
   #   MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: dbname
      MARIADB_USER: username
      MARIADB_PASSWORD: password
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    expose:
      - "3306"